[package]
name = "commitmentScheme"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
crypto = "0.2"
sha2 = "0.9.8"
